### ISSUE TITLE
Stackblitz Template?

### ISSUE THREAD

**Issue by hughanderson4** [HTMLElements/smart-webcomponents#1]
Hi, I would like to try out some ideas and run a few prototypes before investing more time in this lib.

Would it be possible to provide a Stackblitz template to quickly try out some things?

Specifically, I need to know if I can use allow-cells-wrap with infinitescroll, combo of these 2 demos:
https://www.htmlelements.com/angular/demos/grid/allow-cells-wrap/
https://www.htmlelements.com/angular/demos/grid/infinitescroll/

If it is supported we will migrate from ag-grid, who forbids such combination of options.

Thanks so much.  🍺

**Comment by bmarkov** [comment]
Hi, 

We prepared a combination of these two demos in Stackblitz: https://stackblitz.com/github/htmlelements/smart-webcomponents-angular/tree/master/grid/overview

Hope this helps.

Best Regards,
Boyko

**Comment by hughanderson4** [comment]
Thanks so much!  It is some great functionality.

🍺
