### ISSUE TITLE
Using 'phone' editor for a gid columns: country issue (multiple same country code), auto edit smart-input width not good, auto add don't show 'phone' editor

### ISSUE THREAD

**Issue by gbrault** [HTMLElements/smart-webcomponents#106]
**Describe the bug**

- Using a grid component 
    - with a column with 'phone' as the editor
    - with the auto add/edit feature (generating a dialog)
-  3 shortcomings
    - In the edit autogen dialog, the width of the phone widget is to short (can't see the number)
    - Using the UK flag, it switch to guernsey while editing the number
    - The add autogen dialog don't take into account the phone editor

**To Reproduce**
Create an app with grid and phone editor and auto add/edit feartures enabled
```
editing: {
    enabled: true,
    mode : 'row',
    action: 'none',
    addDialog: {
        enabled: true,
    },
    addNewRow: {
        visible: true,
        position: 'both'
    },
    dialog:{
        enabled: true,
        width: "15%"
    },
    commandColumn: {
        visible: true,
        position: 'far'
    }                    
},                
```

```
columns: [
	{ label: '#', dataField: 'id', /*width: 5,*/ allowEdit: false },
	{ label: 'First Name', dataField: 'firstname'/*, width: 50*/ },
	{ label: 'Last Name', dataField: 'lastname'/*, width: 50*/ },
	{ label: 'Address', dataField: 'address'/*, width: 150*/ },
	{ label: 'City', dataField: 'city'/*, width: 50 */},
        { label: 'Postal Code', dataField: 'postal_code'/*, width: 50*/ },
        { label: 'Country', dataField: 'country'/*, width: 50*/ },
        { label: 'Phone', 
          dataField: 'phone',
          editor: 'phone'
        },
        { label: 'LinkedIn', dataField: 'linkedin'/*, width: 150*/ },
        { label: 'Birthday', dataField: 'birthday'/*, width: 50*/ },
        { label: 'Email', dataField: 'email'/*, width: 50*/ },		
]
```

1. I set the flag to uk and it turns to Guernsey when I start editing the number
2. You can see on the image the phone field is too small

![image](https://github.com/HTMLElements/smart-webcomponents/assets/7886676/c9a2324e-942b-48fe-90fe-3733fc5c6f44)

The add dialogue don't have the 'phone' editor

![image](https://github.com/HTMLElements/smart-webcomponents/assets/7886676/7a39b26e-71f7-49c0-8421-4d337a49ca4f)

**Comment by bmarkov** [comment]
fixed
