### ISSUE TITLE
Should I give Restricted Hours API for Grouped Schedular (Doctor Schedular) ?

### ISSUE THREAD

**Issue by DivyarajsinhRana** [HTMLElements/smart-webcomponents#124]
I have designed doctor schedular component using Smart Schedular Component. In have to give  restricted hours property to all doctor listed in schedular . Current restricted hours property is only limited to simple schedular i.e. schedular without resources.

My All Doctors have different restricted hours.

**Comment by bmarkov** [comment]
The property will be extended in the future versions. Thank you for the feature request!
