### ISSUE TITLE
Does your blazer server side grid provide virtual scrolling paging, export, search features

### ISSUE THREAD

**Issue by swiftinitdotcom** [HTMLElements/smart-webcomponents#13]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bmarkov** [comment]
Yes, we are in the process of building demos and documentation about that. The scheduled release will be in first week of May.
