### ISSUE TITLE
How to use in ASP MVC Core to build a portal

### ISSUE THREAD

**Issue by weedkiller** [HTMLElements/smart-webcomponents#16]
Hello, can you share some samples on how to use in MVC core and host on Linux.

Also a simple architecture view of how developers can build `ViewComponents ` or partialViews components/pieces of this to reuse from their back end.

Lastly can you share a portal demo with widgets that can have common things like settings, print, export to excel pdf, etc. We want to let user change the chart type inside the dashboard

![image](https://user-images.githubusercontent.com/21086190/124365529-af196380-dc16-11eb-9413-4d403d66ce29.png)

**Comment by bmarkov** [comment]
You can look at https://www.jqwidgets.com/jquery-widgets-documentation/documentation/asp.net-integration/asp.net-chart-sql-database.htm. It explains how to use jQWidgets with ASP.NET MVC. With Smart UI, the approach could be similar, but we still do not have any help tutorials about it.
