### ISSUE TITLE
Smart Query Builder not firing the "change" event when clearing a group condition after setting the value on run time

### ISSUE THREAD

**Issue by alonso-kleeen** [HTMLElements/smart-webcomponents#26]
**Describe the bug**
When using the Smart Query Builder, you can set dynamically the component's value property during run time, and it properly displays visually. But after doing that, if you click on the "x" button, the "change" event does not fire.

**To Reproduce**
1. Set up the component in this way (here I'm using it inside of a Lit component):
```html
<smart-query-builder
  id="querybuilder"
  .allowDrag=${true}
  .showIcons=${false}
  .fields=${[
    { label: 'My Field 1', dataField: 'field1', dataType: 'string' },
    { label: 'My Field 2', dataField: 'field2', dataType: 'string' },
  ]}
  @change=${this.onSmartQueryBuilderChange}
></smart-query-builder>
```

Where the listener function looks like this:

```typescript
onSmartQueryBuilderChange(event: Event) {
  console.log(`received smart query builder change event`, event)
}
```

2. Change the query builder's value programmatically after a couple of seconds. For example:
```typescript
setTimeout(() => {
  this.smartQueryBuilder.value = [['field1', '=', '123']]
}, 2000)
```
3. Check the filter appears in the UI, and then click on the "x" next to it:

![image](https://user-images.githubusercontent.com/56039061/171292614-ff46f50f-8861-4372-95ea-2e7c6b653d0c.png)

4. Check the browsers log to check the emitted event fired when you changed the current query on step 3.

**Expected behavior**
A change event should fire up since the value changed.

**Screenshots**
Notice the missing log when I click on the x button:
![missing-change-event](https://user-images.githubusercontent.com/56039061/171292963-a99d1979-178f-4b74-8791-3ba43fe81881.gif)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 102

**Additional context**
The event does fire if you set the value programmatically more than once in a row.

**Comment by bmarkov** [comment]
resolved for the upcoming release
