### ISSUE TITLE
Smart Query Builder: value fired inthe "change" event is not the current one

### ISSUE THREAD

**Issue by alonso-kleeen** [HTMLElements/smart-webcomponents#27]
**Describe the bug**
When using the Smart Query Builder, you can subscribe for changes by listening for the "change" event. However, when setting the value dynamically (by directly setting the value property) the payload received in the event is not up to date.

**To Reproduce**
1. Set up the component in this way (here I'm using it inside of a Lit component):
```html
<smart-query-builder
  id="querybuilder"
  .allowDrag=${true}
  .showIcons=${false}
  .fields=${[
    { label: 'My Field 1', dataField: 'field1', dataType: 'string' },
    { label: 'My Field 2', dataField: 'field2', dataType: 'string' },
  ]}
  @change=${this.onSmartQueryBuilderChange}
></smart-query-builder>
```

Where the listener function looks like this:

```typescript
onSmartQueryBuilderChange(event: Event) {
  console.log(`received smart query builder change event`, event)
}
```

2. Change the query builder's value programmatically after a couple of seconds. For example:
```typescript
setTimeout(() => {
  this.smartQueryBuilder.value = [['field1', '=', '123']]
}, 2000)
```

4. Check the browsers log and look at the event's detail.value field. It's an empty array (the value previous to being updated).

**Expected behavior**
Event.detail.value should contain "[['field1', '=', '123']]" which is what was dynamically set.

**Screenshots**
![missing-detail-value](https://user-images.githubusercontent.com/56039061/171294171-75b20fa9-1f90-4000-8314-832425a75333.gif)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 102

**Additional context**
It looks like the event contains the value BEFORE it was updated to the new set value.

**Comment by bmarkov** [comment]
resolved in upcoming release.
