### ISSUE TITLE
Date on tool tip is off by day

### ISSUE THREAD

**Issue by rmalired** [HTMLElements/smart-webcomponents#28]
**Describe the bug**
When rendering time series data, the tool tip shows wrong day when x-axis is marked as type 'date'

**To Reproduce**

Sample Data:

[
{"Date":"2022-05-01","As Is Performance":72},
{"Date":"2022-05-02","As Is Performance":73},
{"Date":"2022-05-03","As Is Performance":1E+2},
{"Date":"2022-05-04","As Is Performance":123},
{"Date":"2022-05-21","As Is Performance":82},
{"Date":"2022-05-25","As Is Performance":18},
{"Date":"2022-06-05","As Is Performance":51},
{"Date":"2022-06-06","As Is Performance":57}
]

chart configuration:

--------------
caption = 'Metric';
        description = 'As Is Performance';
        showLegend = true;
        padding = { left: 30, top: 5, right: 30, bottom: 5 };
        titlePadding = { left: 50, top: 0, right: 0, bottom: 10 };
        dataSource = [];
        colorScheme = 'scheme32';
        xAxis = {
            dataField: 'Date',
            type: 'date', 
            baseUnit: 'month',      
            tickMarks: {
                visible: true,
                unitInterval: 1,
                color: '#BCBCBC'
            },
            gridLines: {
                visible: true,
                unitInterval: 30,
                color: '#BCBCBC'
            }
        };
        clip = true;
        valueAxis = {
            visible: true,
            title: { text: 'Percentage (%)' },
            tickMarks: { color: '#BCBCBC' },
            unitInterval: 30,
            minValue: 0,
            maxValue: 150
        };
        seriesGroups = [
            {
                type: 'line',
                series: [
                    { dataField: 'As Is Performance', displayText: 'As Is', labels: { visible: true, formatSettings: { sufix: '°' } }, symbolType: 'circle', symbolSize: 8 },
                ]
            }
        ];

------------------

**Expected behavior**
The tooltip should show exact day instead of previous day

**Screenshots**
![image](https://user-images.githubusercontent.com/984797/172942176-cd93eba9-f218-4e26-a9ef-0a2ee9d36c5a.png)

**Desktop (please complete the following information):**
 - OS:  windows
 - Browser chrome
 - Version latest

**Comment by bmarkov** [comment]
Hi Rakesh,

In https://codepen.io/jqwidgets/pen/OJQaVgY?editors=1111, we tried to replicate this.

![charting](https://user-images.githubusercontent.com/20238579/172997043-505a6716-bbf9-4e24-9dfe-d2130b5239a7.png)

However, date strings without time zone information i.e not according to the ISO standard for Dates may be +1, -1 when new Date() javascript object is created i.e you can use Date objects instead of strings like that {"Date":new Date(2022, 5, 6),"As Is Performance":57}
];

You can also format the tooltip using the 'tooltipFormatFunction'.

``` chart.toolTipFormatFunction = function (value, itemIndex, serie, group, xAxisValue, xAxis) {
                return value;
            }
```
