### ISSUE TITLE
export and print

### ISSUE THREAD

**Issue by rmalired** [HTMLElements/smart-webcomponents#29]
**Is your feature request related to a problem? Please describe.**
the saveAsJPEG, saveAsPNG, saveAsPDF can be shown icons on right hand corner of chart

**Describe the solution you'd like**
for eg: if i consider the following html and have additional input [exportNPrint]

<smart-chart #chart  id="chart" [caption]="caption" [description]="description" [showLegend]="showLegend"
        [padding]="padding" [titlePadding]="titlePadding" [dataSource]="dataSource" [colorScheme]="colorScheme"
        [xAxis]="xAxis" [clip]="clip" [valueAxis]="valueAxis" [seriesGroups]="seriesGroups" [exportNPrint] = ""></smart-chart>

if it renders the inside the chart ( the filename can be defaulted to caption value if exists or default  file name  always)

![image](https://user-images.githubusercontent.com/984797/172945583-b9ac4183-1dd8-4ab7-ab23-fde0a9b723f5.png)

It will improve the developer productivity

**Describe alternatives you've considered**
NA
**Additional context**

**Comment by bmarkov** [comment]
We will consider this in the future.
