### ISSUE TITLE
Style state is not reset when re-rendering cells with virtualization

### ISSUE THREAD

**Issue by rpsirois** [HTMLElements/smart-webcomponents#30]
**Describe the bug**
Cells retain previous style state on re-render.

**To Reproduce**

1. I used the table overview example and simply added the `virtualization` property and removed the manual style reset in the `formatFunction` for the status column (originally line #69).
2. [CodePen](https://codepen.io/rpsirois/pen/OJQqQVj?editors=1010)
3. Scroll the table

**Expected behavior**
Cells are completely re-rendered per the configured format from default (no need to clear dirty state).

**Desktop (please complete the following information):**
 - OS:
    - Distributor ID: Pop
    - Description: Pop!_OS 21.10
    - Release: 21.10
    - Codename: impish
 - Browser: chrome Version 102.0.5005.61 (Official Build) (64-bit)

**Comment by bmarkov** [comment]
The reported issue is invalid. The style should be reset as it is in the example.
