### ISSUE TITLE
Table filterRow string filter options selector does not trigger a re-render

### ISSUE THREAD

**Issue by rpsirois** [HTMLElements/smart-webcomponents#31]
**Describe the bug**
Changing the string filter options with text value already entered does not trigger a re-render.

**To Reproduce**
1. Go to [https://www.htmlelements.com/demos/table/filter-row/](https://www.htmlelements.com/demos/table/filter-row/)
2. Enter something in a row filter like "con panna" in Product Name
3. Change the string filter option to "does not contain"
4. No re-render occurs (even when losing focus on the input). You have to go back into the text input and press Enter.

**Expected behavior**
Table should be responsive to any user input.

Desktop (please complete the following information):
- OS:
    - Distributor ID: Pop
    - Description: Pop!_OS 21.10
    - Release: 21.10
    - Codename: impish
- Browser: chrome Version 102.0.5005.61 (Official Build) (64-bit)

**Comment by bmarkov** [comment]
fixed
