### ISSUE TITLE
Tooltip doesn't open in proper place when implemented in smart-table

### ISSUE THREAD

**Issue by rpsirois** [HTMLElements/smart-webcomponents#33]
**Describe the bug**
`smart-tooltip` doesn't open in the proper place when implemented in `smart-table` (appears to be at 0, 0).

**To Reproduce**
1. [https://codepen.io/rpsirois/pen/GRQaaXN](https://codepen.io/rpsirois/pen/GRQaaXN)
2. Using the table billing history example as a base
3. Change the "Actions" column to render a button with a tooltip just like the tooltip "Basic" example
```
const id = 'tt' + settings.row
                            
// test not dom-connected
const $btn = document.createElement( 'smart-button' )
$btn.setAttribute( 'id', id )
$btn.textContent = 'Button'
  
const $tt = document.createElement( 'smart-tooltip' )
$tt.setAttribute( 'selector', id )
//$tt.selector = $btn
$tt.setAttribute( 'arrow', true )
$tt.textContent = 'This is a tooltip for row ' + settings.row
                          
const $span = document.createElement( 'span' )
                            
$span.append( $btn )
$span.append( $tt )
                            
settings.template = $span
```

**Expected behavior**
Tooltip to show up on button.

Desktop (please complete the following information):

- OS:
    - Distributor ID: Pop
    - Description: Pop!_OS 21.10
    - Release: 21.10
    - Codename: impish
- Browser: chrome Version 102.0.5005.61 (Official Build) (64-bit)

**Comment by bmarkov** [comment]
The tooltip should be added to the table. document.querySelector("#table").appendChild($tt);
