### ISSUE TITLE
Tooltip can't select by ID in shadow DOM

### ISSUE THREAD

**Issue by rpsirois** [HTMLElements/smart-webcomponents#34]
**Describe the bug**
Tooltip is unable to find the target element with `selector` property (when it's a string) in the shadow DOM.

**To Reproduce**
1. Place a tooltip in a shadow dom with a string `selector`
2. Hover on the element with the `id` that `selector` is pointed at
3. Nothing happens ([codepen](https://codepen.io/rpsirois/pen/xxYoKPB?editors=1011))

**Expected behavior**
Tooltip functions as normal.

Desktop (please complete the following information):

- OS:
    - Distributor ID: Pop
    - Description: Pop!_OS 21.10
    - Release: 21.10
    - Codename: impish
- Browser: chrome Version 102.0.5005.61 (Official Build) (64-bit)

**Comment by bmarkov** [comment]
As it is a shadow dom, it is not possible to find elements by using document.querySelector which we use for the tooltip to find the element by using the "selector" property. This scenario is unfortunately not supported by our component.
