### ISSUE TITLE
jQuery conflict with Smart.Grid

### ISSUE THREAD

**Issue by jqwidgets** [HTMLElements/smart-webcomponents#4]
**Describe the bug**

On click of the Filter button, a console error is thrown.

**To Reproduce**

Add jquery.js to any Grid demo.

**Comment by s-cork** [comment]
It looks like the error is thrown from the cell which is proxied but doesn't have a `_properties`. The error thrown is `cannot read enabled of undefined` which comes from `this._properties['enabled']` where `this` is a smart-grid-cell.
