### ISSUE TITLE
Tabbing to maskedtextbox / tabindex not working

### ISSUE THREAD

**Issue by genachka** [HTMLElements/smart-webcomponents#5]
Tried version 8.0.0  smart.maskedtextbox and when using keyboard navigation to tab to it, it doesn't appear to show a selection on focus. I tried tweaking the CSS and when I click on it, I was able to get focus shown, but when setting tabindex attribute or tabbing to it doesn't appear to work.

**Comment by jqwidgets** [comment]
We are unable to reproduce such behavior by testing it online here: https://www.htmlelements.com/demos/maskedtextbox/overview/

If you experience some kind of issue, please provide a full example and steps to reproduce it.

**Comment by genachka** [comment]
Maybe it's an CSS issue then. I want to change the width and color of the on focus box around the control. What CSS class(es) should I set? Because the ones I set do work on focus when I click directly but not on a tab. Here's what I tried:

```
.smart-masked-text-box .smart-input {
     border: 1px solid var(--smart-border);
     background: var(--smart-background);
     overflow: visible;
     border-radius: var(--smart-border-radius);
     padding-left: .75rem;
}
.smart-masked-text-box .smart-input:focus {
     box-shadow: 0 0 0 0.2rem rgba(0,123,255,.25);
}
```

**Comment by bmarkov** [comment]
The CSS variables available for styling the component are describer here: https://www.htmlelements.com/docs/maskedtextbox-css/
