### ISSUE TITLE
Horizontal scrolling and pager issues

### ISSUE THREAD

**Issue by genachka** [HTMLElements/smart-webcomponents#6]
Trying to test out Grid in 8.0.0 via ES 6 module,

Have my import as:
`import {Grid} from 'smart-webcomponents/source/modules/smart.grid';`

And my HTML CSS resource included as:
`<require from="smart-webcomponents/source/styles/smart.default.css"></require>`

In my javascript code, I init it as:
```new Smart('#grid', class {
            get properties() {
                return {
                    behavior: {
                        allowColumnReorder: true,
                        columnResizeMode: 'growAndShrink',
                        allowColumnAutoSizeOnDoubleClick: true
                    },
                    appearance: {
                        alternationCount: 2
                    },
                    paging: {
                        enabled: true,
                        pageSize: 12,
                        summary: {
                            visible: true,
                            position: 'far'
                        },
                        pageSizeSelector: {
                            visible: true
                        }
                    },
                    pager: {
                        visible: true
                    },
                    sorting: {
                        enabled: true
                    },
                    dataSource: new window.Smart.DataAdapter({
                        dataSource: data,
...
```
Value of above `data` is a JSON array that I get from server. And I do get the grid to populate data. The columns don't all fit in the width so there is a horizontal scrollbar displayed on bottom of the grid as I would expect but when I move it to the right to see more data I see the grid only move the header row and the first row while the other rows stay in place as shown in the screen shot:
![image](https://user-images.githubusercontent.com/7947294/97768388-1798c980-1af9-11eb-844e-663b9cce0ee1.png)

And I see this displayed in console as error:
![image](https://user-images.githubusercontent.com/7947294/97768406-34350180-1af9-11eb-978c-063b38dfd128.png)

As as shown on the screen shot, the pager is missing an icon

**Comment by bmarkov** [comment]
There is no {Grid} export in order to import it.  It should be only import 'smart-webcomponents/source/modules/smart.grid' 
Please, share a codepen example which reproduces this
