### ISSUE TITLE
How show "Loading data" or "Refreshing data"

### ISSUE THREAD

**Issue by genachka** [HTMLElements/smart-webcomponents#7]
Both during the initial grid data load and when I user makes an action and I need to refresh the grid's data from a backend API, I want to set the grid to not allow updates, clear the data, and where it would at that point show "No Rows" I want to display a custom message like "Refreshing data" while on the initial load I want to show "Loading data".

I couldn't find any methods in the API documentation to do this. How to accomplish this?

**Comment by bmarkov** [comment]
Loading icon is displayed, when your data source is virtual i.e. when the data is loaded on demand. Examples with Virtual data sources are available here: https://www.htmlelements.com/demos/grid/overview/.

**Comment by genachka** [comment]
Strange response and immediate closing of issue. The link shows a general overview and no specific example. 

Are you saying there is no way to manually set the grid in a state to show a custom message after manually clearing out the data and manually setting the data on refresh? The jquery jqwidgets supports this as do many other grids I've worked with.
